language: cpp
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    packages:
    - libopencv-dev
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../practice5-performance
  - make -j
notifications:
  email: false
